version: "3"
services:
    app:
        build: .
        image: hw_server
        restart: always
        ports:
            - 5000:5000
        depends_on:
            - "db"
    db:
        image: postgres
        environment:
            POSTGRES_USER: postgres
            POSTGRES_DB: hw_db
            POSTGRES_PASSWORD: armatura
